### PR TITLE
Create language_es.properties

### PR DESCRIPTION
**Pull request by OCReactive**
I translated to spanish.

### CODE REVIEW

**Comment by brindosch** [comment]
@OCReactive 
First of all i have to say sorry for the delay.
Second: This is amazing! You are the first person (except me) that created a translation!
Sadly i have to say that we will deprecate HyperCon, as the concept of it is a little bit outdated

But your work isn't lost! If i don't scare you away i would appreciate if you are a part of the future.
To be more concrete, the replacement of HyperCon - a web configuration/control interface.
To make translating easier for everyone we use (since now) POEditor. You could join here: https://poeditor.com/join/project/mwkrs4LN6F

Thank you

**Comment by OCReactive** [comment]
Happy to help!

I was suspecting that with the development of Hyperion.ng HyperCon would be deprecated, but I translated it just in case.

I've almost finised the translation in POeditor, desiring to test a release (when available) to check and fix any fuzzy translation.

Thank you so much for bringing the world such an amazing software.

**Comment by brindosch** [comment]
Thank you,
amazing fast.
I merged the current state. You could compile it following this: https://github.com/hyperion-project/hyperion.ng/blob/master/CompileHowto.md

The browser locale will be used to show you the correct language. I noticed that it seems not to work with a es-ES Firefox locale. I will debug and report back.

You could switch languages at the top (globe icon)
If you have any question just write it down. (I didn't expected to setting up translation service that early :) - so further explanations for tokens are missing. Or a short overview what means what.)

**Comment by brindosch** [comment]
All good. false positive :)

**Pull request merged**
