### PR TITLE
Created gradle and travis configurations

### PR DESCRIPTION
**Pull request by WoLpH**
Some basic configuration to make testing easier :)
Using this we have automated building and it makes building the app much easier for new users.

The test results: https://travis-ci.org/WoLpH/hypercon

### CODE REVIEW

**Comment by brindosch** [comment]
Greetings @WoLpH 
thank you for your participation!
As already written with Rick, don´t invest too much time here :)

**Comment by WoLpH** [comment]
I just wanted to fix the most annoying bugs. In retrospect it seems that it mostly works pretty ok but windows doesn't set the working directory to a writable path apparently. 

I had no large issues when running it from os x.

**Comment by brindosch** [comment]
> windows doesn't set the working directory to a writable path apparently

I can't follow you, which component? I worked at HyperCon on Windows with Eclipse Java IDE and saw no issues?

I am aware of the errors at SSH listener and the never used ssh interface. Thank you :)

**Comment by WoLpH** [comment]
It could very well be an environmental issue. I was running hypercon.jar
straight from the Firefox downloads window and when reopening hypercon.jar
later all settings were gone again which makes me think the working
directory is set to a non-writable directory.

Since manual saving and loading the settings appears to leave out a few
settings I was just debugging it a little :)
But it's all good enough for the time being so let's look forward to the
next version.

**Comment by brindosch** [comment]
> Since manual saving and loading the settings appears to leave out a few
settings I was just debugging it a little :)

The only setting that is currently not saved is the device part.
Is annoying but i could stick with it.

The biggest problem of HyperCon itself is the java framework, it is not really a future driven idea to use a java tool to create a simple .json output. Only the nice tv frame virtualization might be hard to create at a lower level in Javascript.
Also due to the point you could run hyperion as often you want now: HyperCon needs in most parts a big rework and a move to JSON.
And you still can't use HyperCon on a smartphone or tablet and the UI differ extremely between MacOS-Windows-Linux so the ui layout is not that great on all platforms.

So in sum, it is not really worth to invest too much time and develop it further. It is possible but it is more a time waste.

The installation of Hyperion could be later done with a small qt application whichs is really just written for this step. (already have a nice idea how this could be done with a great (easy) user experience)

**Comment by WoLpH** [comment]
I agree, java definitely isn't the best option here. I think a web based approach is a very nice option though. Should work a lot easier for the users since it makes the setup somewhat easier.

I'm looking forward to the new javascript interface and I'm definitely interested in helping. To make the server-client interaction a tad easier we could use a framework such as Angular: https://angular.io/
That's far from the only option though, but it shouldn't be too hard to make something pretty with a bit of javascript :)

**Comment by brindosch** [comment]
We may just work with the browser DOM, at least mostly. So the backend would be not that big. There are a few /cgi calls implemented currently to trigger something like a .json read.

Due to the point we use JSON RPC and all(most) options should be available to configure (think about home automation systems and other stuff) we could stick with just a browser based "processing"

The other point is why we may get a problem with the "backend logic" is the hyperion forwarder (multiple instances). So it may be easier to call avahi to get all instances and then get the port you need to requests the current options/values and build afterwards an interface with them.

**Comment by WoLpH** [comment]
Fair enough, no need for anything too complicated here. I'll see if I can create a little example interface to resemble hypercon a little :)

**Comment by brindosch** [comment]
I am not that familiar with web technics, we use what makes sense so the decision is not final :). New ideas and other frameworks which brings new possibilities to reuse the code for "other" things or "React Native" Applications on top.
We have currently the possibility to create something completely new. So we should stick with the right technics/frameworks :)

**Comment by WoLpH** [comment]
@brindosch perhaps we should continue the discussion on the forum? Anywho, I've created a tiny little demo using a bit of css, html and javascript :)

**Pull request merged**
