### PR TITLE
add LibreELEC specific support

### PR DESCRIPTION
**Pull request by lrusak**
This treats OpenELEC and LibreELEC as different systems

We have hyperion available in our add-on repository so we can use that. I have added a specific LibreELEC system that will use the paths that are used for the add-on.

If I missed anything please let me know.

### CODE REVIEW

**Comment by Starbix** [comment]
This could break Plex Media Player support in the future, when PMP gets assigned to LibreELEC, because there's no .kodi directory.

**Comment by lrusak** [comment]
Then you just select OpenELEC from the drop down. Boom works.

Or create another system type.

**Comment by Starbix** [comment]
Yeah I know, but it'll get confusing because PMP is based on LibreELEC

**Comment by brindosch** [comment]
Greetings,
thank you for your contribution.
Sadly HyperCon will be discontinued once we are ready.
A build in update system is planned. In future we use also systemd for OE/LE.
How we manage this with your libreelec hyperion is another story.

**Comment by lrusak** [comment]
So if Hypercon is dead is there some configuration method built into hyperion-ng?

**Comment by tpmodding** [comment]
yes, it has a webinterface to configure everything

**Pull request closed without merging**
